"""init create tables

Revision ID: 562668b878f7
Revises: 
Create Date: 2020-08-29 22:25:55.706543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562668b878f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
